name = "Mc Vanilla Enhanced 1 . 21 . 1"
author = "moritz-grimm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0414146c9d78704086de34e2cb133218ba7fdf611d91125d77e5d7324ebc4efb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
