name = "Mc Vanilla Enhanced 1 . 21 . 1"
author = "moritz-grimm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2bd0f39f5cf73d74dfa65805c12936c026ab0d74401dd1bf177d078d9ff9ea7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
