name = "Mc Vanilla Enhanced 1 . 21 . 1"
author = "moritz-grimm"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef5c20913ac9b0e757dbe0226506f0a42a0180ecfb7c2ea51b8fc597bf27bfe5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
